# Generated by Django 6.0.4 on 2026-04-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.CharField(choices=[('A', 'A조(10년)'), ('B', 'B조(5년)'), ('C', 'C조(3년미만)')], max_length=1)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.IntegerField(choices=[(2, '2코트'), (3, '3코트')])),
                ('p1_score', models.IntegerField(blank=True, null=True)),
                ('p2_score', models.IntegerField(blank=True, null=True)),
                ('applied_handicap', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.monthlymeet')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to='matches.profile')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to='matches.profile')),
            ],
        ),
    ]
