# Generated by Django 6.0.4 on 2026-04-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='사장님 권한'),
        ),
    ]
