# Generated by Django 6.0.4 on 2026-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_profile_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlymeet',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='마감 여부'),
        ),
    ]
