# Generated by Django 6.0.4 on 2026-04-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_notice_author_notice_author_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
