# Generated by Django 6.0.4 on 2026-04-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_notice_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, verbose_name='로그 레벨')),
                ('message', models.TextField(verbose_name='로그 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 일시')),
            ],
            options={
                'verbose_name': '시스템 로그',
                'verbose_name_plural': '시스템 로그 목록',
            },
        ),
    ]
